### ISSUE TITLE
About Description

### ISSUE THREAD

**Issue by jgarte** [BonfaceKilz/tsaf-analysis-of-bxd-mouse-colonies#1]
Hi Bonface,

Could you add a description to this notebook in the project page? 

`binderlite` [will pick it up](https://git.genenetwork.org/jgart/binderlite/src/branch/master/app.py#L93) and use it which will [look nice](http://notebook.genenetwork.org/).

**Comment by BonfaceKilz** [comment]
Thanks.  I've just added a brief description.  Thanks for the reminder!

**Comment by jgarte** [comment]
no prob, thank you!
